### ISSUE TITLE
Use pytorch to run the lua in eval?

### ISSUE THREAD

**Issue by hughperkins** [jcjohnson/densecap#1]
Hi,

Noticed you have python calling java, and then communicating with lua via json files.

Just so you know, pytorch lets you run lua classes directly from python :-)

pytorch is here: https://github.com/hughperkins/pytorch

Example usage here:
- https://github.com/hughperkins/cifar.pytorch
- https://github.com/hughperkins/pytorch-residual-networks

**Comment by hughperkins** [comment]
(since this isnt an issue, but just for info, I will close this)

**Comment by YanjunChen** [comment]
Is there a pytorch version of this code?

**Comment by jcjohnson** [comment]
Hugh was talking about a previous project called pytorch which is unrelated to the new framework from FAIR.

There is not yet a PyTorch implementation of DenseCap as far as I know.

**Comment by YanjunChen** [comment]
@jcjohnson Thanks!
