### ISSUE TITLE
Why does Languagemodel creates view with -1 size, and then resized during updateoutput

### ISSUE THREAD

**Issue by wenhuchen** [jcjohnson/densecap#16]
In the LanugageModel.lua, I noticed that when view_in, view_out are created, they took size of -1. But they resize into (N * (T + 2), -1) during UpdateOutput, in line 122/123. 
Is there any specific reason to do that?

**Comment by wenhuchen** [comment]
seems I already know the answer, is it because only in UpdateOutput function can we get the actual batch size?

**Comment by jcjohnson** [comment]
Yep, you figured it out =)
