### ISSUE TITLE
Problem running client/server webcam demo

### ISSUE THREAD

**Issue by mkhademi** [jcjohnson/densecap#24]
Hi @jcjohnson,

I followed your instruction to run the client/server webcam demo. I was able to generate my self-signed signature on my server. When I point my client browser to the following address with SERVER_URL replaced by my server ip-address, i.e.:
https://cs.stanford.edu/people/jcjohns/densecap/demo/web-client.html?server_url=SERVER_URL

I see the following:
![image](https://cloud.githubusercontent.com/assets/1362108/17417015/e4d9a460-5a45-11e6-88d1-0bfc6014fea5.png) but none of the buttons work! It seems they are disabled

Even if I point my client browser directly to my server ip-address, it does not show me anything to let the browser manually know that the server is trusted. I tried with chrome, firefox and ie but neither of them worked.

I appreciate your help!

**Comment by jcjohnson** [comment]
A couple of things to debug:

(1) In the terminal tab that is running the server, do you see the requests going through to the server? Are there any error messages there?

(2) Are there any errors in the Javascript console?

**Comment by mkhademi** [comment]
Thanks Justin for your prompt answer. On the server side, I do not see any errors. As you mentioned in the instruction, it seems both of them are running for ever. Here are the outputs:

$th webcam/daemon.lua
loading checkpoint from data/models/densecap/densecap-pretrained-vgg16.t7
done loading checkpoint

$python webcam/server.py
--does not show any output

---------------------------------------------------
On the client JS console: it says: Failed to load, error connection closed, 404 (Not Found). Probably because of the SSL authentication. But I do not know where to fix it!

Btw, the ip-address I am using for my URL server works fine in case of visualization of random images assuming I replace "localhost" with that in the following address:
http://localhost:8181/view_results.html 

Thanks!

**Comment by jcjohnson** [comment]
Did you by some chance start the web server using `python -m SimpleHTTPServer 8181`? You should be starting it by just running `python webserver/server.py`; the latter should be listening on port 5000 instead of port 8181, and should not be able to serve files such as `view_results.html`.

**Comment by mkhademi** [comment]
No, I only used: python webserver/server.py

From the previous comment, I just wanted to tell you that although the error shows 404, but my ip-address works fine when I use it with this command: http://server-ip:8181/view_results.html

So basically the only thing I can think of is SSL. For some reason I cannot see the page you showed in the instruction to manually set the server is trusted and because of that it gives the "fail to load" error.

**Comment by mkhademi** [comment]
Hi @jcjohnson, I played a little bit more with that and here is the error that I get from the server side:

$python webcam/server.py

WARNING:tornado.general:SSL Error on 9 ('10.101.139.48', 63041): [SSL: HTTP_REQUEST] http request (_ssl.c:590)

Does that ring a bell?

Thanks!

**Comment by mkhademi** [comment]
It works now. The problem was that I was not including the port number in the server URL. After including 5000, it worked!

**Comment by jcjohnson** [comment]
Awesome, glad to hear it!

Sorry I couldn't be of more help - I don't *really* know what I'm doing
when it comes to web dev / SSL / etc.

**Comment by mkhademi** [comment]
No worries! This is an awesome work and the instruction to get the code up and running was pretty straight forward. Thanks for sharing it!

**Comment by sampathchanda** [comment]
@mkhademi Can you please elaborate on, how you fixed the issue by including the port number in the server URL ?
I am also getting the same error message as you mentioned.

**Comment by sampathchanda** [comment]
I got this working. To make things clear for another person trying this out, following fixed the issue.
As mentioned in the steps, point out your browser at client side to the server url with port as below, first:
`https://<server-ip>:5000/`

After accepting the certificate, you can use this server url along with the port number in place of the `SERVER_URL`, in the following url:
`https://cs.stanford.edu/people/jcjohns/densecap/demo/web-client.html?server_url=SERVER_URL`

**Comment by kilmarnock** [comment]
I have a problem I could nail down:
`https://localhost:5000/` shows `The DenseCap server seems to be running!`

`https://cs.stanford.edu/people/jcjohns/densecap/demo/web-client.html?server_url=localhost:5000`
 gives
 `WARNING:tornado.general:error on read: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1754)` 
on the sever side.

According to [https://stackoverflow.com/questions/37356579/python-ssl-server-reporting-tlsv1-alert-unknown-ca](url), it is a problem of the server accepting the browser certificate? Anyone seen this? I would install a ca, but I do not which ca is responsible now.
