### ISSUE TITLE
why no 'TemporalCrossEntropyCriterion'

### ISSUE THREAD

**Issue by lemondan** [jcjohnson/densecap#25]
Hi, I am running your densecap code. But in the DenseCapModel.lua L120, it attempts to call field 'TemporalCrossEntropyCriterion'. But there is no definition about TemporalCrossEntropyCriterion. The errors show that the module TemporalCrossEntropyCriterion is not found. Could you help it?

**Comment by soumith** [comment]
update your torch-rnn package:
luarocks install https://raw.githubusercontent.com/jcjohnson/torch-rnn/master/torch-rnn-scm-1.rockspec
