### ISSUE TITLE
Very minor README issue

### ISSUE THREAD

**Issue by ageitgey** [jcjohnson/densecap#3]
This is a very minor issue. I just wanted to point out that the README says:

`To run the pretrained model on the provided elephant.jpg image...`

But `elephant.jpg` isn't actually included anywhere in the repo.

Thanks!

**Comment by jcjohnson** [comment]
Sorry about that - should be fixed now.

**Comment by truell20** [comment]
I believe that this should be closed.

**Comment by ageitgey** [comment]
Thanks!
