### ISSUE TITLE
‘Unknown object‘ error when start to run the run_model.lua.

### ISSUE THREAD

**Issue by hitfishking** [jcjohnson/densecap#30]
I followed the instructions and tried to start running the model on a new image(elephant.jpg), but I got an "Unknow object" error as follows:

hitfishking@ubuntu:~/densecap$ th run_model.lua -gpu -1 -input_image ~/densecap/imgs/elephant.jpg 
/home/hitfishking/torch/install/bin/luajit: ...e/hitfishking/torch/install/share/lua/5.1/torch/File.lua:375: unknown object
stack traceback:
        [C]: in function 'error'
        ...e/hitfishking/torch/install/share/lua/5.1/torch/File.lua:375: in function 'readObject'
        ...e/hitfishking/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
        ...e/hitfishking/torch/install/share/lua/5.1/torch/File.lua:353: in function 'readObject'
        ...e/hitfishking/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
        ...e/hitfishking/torch/install/share/lua/5.1/torch/File.lua:353: in function 'readObject'
        ...e/hitfishking/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
        ...e/hitfishking/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
        /home/hitfishking/torch/install/share/lua/5.1/nn/Module.lua:158: in function 'read'
        ...e/hitfishking/torch/install/share/lua/5.1/torch/File.lua:351: in function 'readObject'
        ...e/hitfishking/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
        ...e/hitfishking/torch/install/share/lua/5.1/torch/File.lua:409: in function 'load'
        run_model.lua:146: in main chunk
        [C]: in function 'dofile'
        ...king/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
        [C]: at 0x0804cbc0

OS: unbuntu Desktop 15.05, 32bit.
Anything wrong with my system configuration? Anyone can help?

**Comment by hitfishking** [comment]
**Seems figured out the problem!** 
The  above problem was triggered on a desktop machine with 

> ubuntu Desktop 15.05, 32bit

.
Inspired by the solution of the post https://groups.google.com/forum/#!topic/torch7/zNNdXATZxlA, I shifted to another machine with

>  ubuntu server 16.04, 64bit

, the problem disapeared! 
It may be related with file format of the .t7 model file or some other files. I'm not sure.

**Comment by jcjohnson** [comment]
I think the problem is that the model was serialized on a 64-bit OS; Torch can't read this file on a 32-bit OS.
