### ISSUE TITLE
Warning: cudnn.convert does not work with nngraph yet.

### ISSUE THREAD

**Issue by xpchen0** [jcjohnson/densecap#35]
Hello ,I am new to this direction and trying the densecap code.But I run the script as fellow:
` ./../densecap-master$ th run_model.lua -input_image ./imgs/t01f0d6d1b73d08a815.jpg `
 I meet the problem like this:
`Warning: cudnn.convert does not work with nngraph yet. Ignoring nn.gModule1/1 processing image ./imgs/t01f0d6d1b73d08a815.jpg	`

I tried this:
```
luarocks install cutorch
luarocks install cunn
luarocks install cudnn
```
But it had no use.
How can I fix it? 
I am new here. Thank you so much.

**Comment by jcjohnson** [comment]
https://github.com/jcjohnson/densecap/issues/34

**Comment by soumith** [comment]
@xpchen0 that's just a Warning, not an error. you can safely ignore it.

**Comment by xpchen0** [comment]
@soumith thank you so much ~
