### ISSUE TITLE
preprocess.py runtime too long!!

### ISSUE THREAD

**Issue by vanpersie32** [jcjohnson/densecap#43]
I tried to preprocess genome dataset with preprocess.py.But it takes too long time. It has taken more than 12 hours before preprocessing half of the dataset. My god!!!!

**Comment by jcjohnson** [comment]
That seems a bit too long. Are you reading or writing to network-attached storage?

**Comment by vanpersie32** [comment]
no,I just read images and json file from my local disk and write h5 and json file to it. Maybe my computer should be equipped with a ssd.

**Comment by vanpersie32** [comment]
The h5 and json file are very big in size, they are more than 50GB before half of all images are preprocessed.
