### ISSUE TITLE
module 'torch-rnn' not found:No LuaRocks module found for torch-rnn

### ISSUE THREAD

**Issue by loveJasmine** [jcjohnson/densecap#48]
rzai@rzai00:~/prj/densecap$ th train.lua 
/home/rzai/torch/install/bin/luajit: /home/rzai/torch/install/share/lua/5.1/trepl/init.lua:384: /home/rzai/torch/install/share/lua/5.1/trepl/init.lua:384: /home/rzai/torch/install/share/lua/5.1/trepl/init.lua:384: module 'torch-rnn' not found:No LuaRocks module found for torch-rnn
	no field package.preload['torch-rnn']
	no file '/home/rzai/.luarocks/share/lua/5.1/torch-rnn.lua'
	no file '/home/rzai/.luarocks/share/lua/5.1/torch-rnn/init.lua'
	no file '/home/rzai/torch/install/share/lua/5.1/torch-rnn.lua'
	no file '/home/rzai/torch/install/share/lua/5.1/torch-rnn/init.lua'
	no file './torch-rnn.lua'
	no file '/home/rzai/torch/install/share/luajit-2.1.0-beta1/torch-rnn.lua'
	no file '/usr/local/share/lua/5.1/torch-rnn.lua'
	no file '/usr/local/share/lua/5.1/torch-rnn/init.lua'
	no file '/home/rzai/.luarocks/lib/lua/5.1/torch-rnn.so'
	no file '/home/rzai/torch/install/lib/lua/5.1/torch-rnn.so'
	no file '/home/rzai/torch/install/lib/torch-rnn.so'
	no file './torch-rnn.so'
	no file '/usr/local/lib/lua/5.1/torch-rnn.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
	[C]: in function 'error'
	/home/rzai/torch/install/share/lua/5.1/trepl/init.lua:384: in function 'require'
	train.lua:17: in main chunk
	[C]: in function 'dofile'
	...rzai/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00406670
rzai@rzai00:~/prj/densecap$

**Comment by jcjohnson** [comment]
You need to install torch-rnn, like this:

```bash
luarocks install https://raw.githubusercontent.com/jcjohnson/torch-rnn/master/torch-rnn-scm-1.rockspec
```

**Comment by loveJasmine** [comment]
thanks
