### ISSUE TITLE
module 'stn' not found:No LuaRocks module found for stn

### ISSUE THREAD

**Issue by loveJasmine** [jcjohnson/densecap#49]
rzai@rzai00:~/prj/densecap$ th train.lua 
/home/rzai/torch/install/bin/luajit: /home/rzai/torch/install/share/lua/5.1/trepl/init.lua:384: /home/rzai/torch/install/share/lua/5.1/trepl/init.lua:384: /home/rzai/torch/install/share/lua/5.1/trepl/init.lua:384: /home/rzai/torch/install/share/lua/5.1/trepl/init.lua:384: module 'stn' not found:No LuaRocks module found for stn
	no field package.preload['stn']
	no file '/home/rzai/.luarocks/share/lua/5.1/stn.lua'
	no file '/home/rzai/.luarocks/share/lua/5.1/stn/init.lua'
	no file '/home/rzai/torch/install/share/lua/5.1/stn.lua'
	no file '/home/rzai/torch/install/share/lua/5.1/stn/init.lua'
	no file './stn.lua'
	no file '/home/rzai/torch/install/share/luajit-2.1.0-beta1/stn.lua'
	no file '/usr/local/share/lua/5.1/stn.lua'
	no file '/usr/local/share/lua/5.1/stn/init.lua'
	no file '/home/rzai/.luarocks/lib/lua/5.1/stn.so'
	no file '/home/rzai/torch/install/lib/lua/5.1/stn.so'
	no file '/home/rzai/torch/install/lib/stn.so'
	no file './stn.so'
	no file '/usr/local/lib/lua/5.1/stn.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
	[C]: in function 'error'
	/home/rzai/torch/install/share/lua/5.1/trepl/init.lua:384: in function 'require'
	train.lua:17: in main chunk
	[C]: in function 'dofile'
	...rzai/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00406670
rzai@rzai00:~/prj/densecap$ luarocks install stn

Error: No results matching query were found.

**Comment by loveJasmine** [comment]
it can be fix byL

rzai@rzai00:~/prj/densecap$ luarocks install https://raw.githubusercontent.com/qassemoquab/stnbhwd/master/stnbhwd-scm-1.rockspec

**Comment by nilinykh** [comment]
just an update for those who might experience the next issue after installing stn from the answer above:
`nvcc fatal   : Value 'sm_20' is not defined for option 'gpu-architecture'`

Experience you this problem, manually change CMakeLists.txt in your cloned github repo, line 55 in particular:
from:
`IF (CUDA_FOUND)
   LIST(APPEND CUDA_NVCC_FLAGS "-arch=sm_20")`
to
`IF (CUDA_FOUND)
   LIST(APPEND CUDA_NVCC_FLAGS "-arch=sm_30")`

and run `luarocks make stnbhwd-scm-1.rockspec`, not `luarocks install stnbhwd-scm-1.rockspec`

my configuration:
CUDA 9.2, Ubuntu 16.04
