### ISSUE TITLE
loadcaffe is also a dependence.

### ISSUE THREAD

**Issue by jessejohns** [jcjohnson/densecap#5]
I get the following error when trying to run the pre-trained model:

`not found:No LuaRocks module found for loadcaffe `

**Comment by soumith** [comment]
Have you tried installing loadcaffe via:

luarocks install loadcaffe

**Comment by jcjohnson** [comment]
I intended for loadcaffe only to be required for training, but there was an import I missed. Should be fixed in https://github.com/jcjohnson/densecap/commit/e84cece7f0476c344b23a7269533bdadb2d30ca8.

**Comment by jessejohns** [comment]
Right.  I thought it would be an odd dependence...  This change works.  Thanks!
