### ISSUE TITLE
module 'libcustn' not found:No LuaRocks module found for libcustn

### ISSUE THREAD

**Issue by puddinord** [jcjohnson/densecap#53]
> 	no field package.preload['libcustn']
	no file '/home/zhangcheng/.luarocks/share/lua/5.1/libcustn.lua'
	no file '/home/zhangcheng/.luarocks/share/lua/5.1/libcustn/init.lua'
	no file '/home/zhangcheng/torch/install/share/lua/5.1/libcustn.lua'
	no file '/home/zhangcheng/torch/install/share/lua/5.1/libcustn/init.lua'
	no file './libcustn.lua'
	no file '/home/zhangcheng/torch/install/share/luajit-2.1.0-beta1/libcustn.lua'
	no file '/usr/local/share/lua/5.1/libcustn.lua'
	no file '/usr/local/share/lua/5.1/libcustn/init.lua'
	no file '/home/zhangcheng/.luarocks/lib/lua/5.1/libcustn.so'
	no file '/home/zhangcheng/torch/install/lib/lua/5.1/libcustn.so'
	no file '/home/zhangcheng/torch/install/lib/libcustn.so'
	no file './libcustn.so'
	no file '/usr/local/lib/lua/5.1/libcustn.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
	[C]: in function 'error'
	/home/zhangcheng/torch/install/share/lua/5.1/trepl/init.lua:384: in function 'require'
	run_model.lua:5: in main chunk
	[C]: in function 'dofile'
	...heng/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00406670

**And I tried to use `luarocks install libcustn`. It dosen't work .**

> Error: No results matching query were found.

**Comment by puddinord** [comment]
what is libcustn?

**Comment by jcjohnson** [comment]
It's the CUDA library for bilinear sampling, from this repository:

https://github.com/qassemoquab/stnbhwd

As mentioned in the densecap README you can install it like this:

```
luarocks install https://raw.githubusercontent.com/qassemoquab/stnbhwd/master/stnbhwd-scm-1.rockspec
```

**Comment by puddinord** [comment]
Thank you! It is solved

**Comment by zs72** [comment]
I run your code. I facing this error.

$ th run_model.lua -input_image imgs/elephant.jpg 
/home/mrrl/torch/install/bin/luajit: /home/mrrl/torch/install/share/lua/5.1/trepl/init.lua:389: module 'densecap-master/densecap/DenseCapModel' not found:No LuaRocks module found for densecap-master/densecap/DenseCapModel
	no field package.preload['densecap-master/densecap/DenseCapModel']
	no file '/home/mrrl/.luarocks/share/lua/5.1/densecap-master/densecap/DenseCapModel.lua'
	no file '/home/mrrl/.luarocks/share/lua/5.1/densecap-master/densecap/DenseCapModel/init.lua'
	no file '/home/mrrl/torch/install/share/lua/5.1/densecap-master/densecap/DenseCapModel.lua'
	no file '/home/mrrl/torch/install/share/lua/5.1/densecap-master/densecap/DenseCapModel/init.lua'
	no file './densecap-master/densecap/DenseCapModel.lua'
	no file '/home/mrrl/torch/install/share/luajit-2.1.0-beta1/densecap-master/densecap/DenseCapModel.lua'
	no file '/usr/local/share/lua/5.1/densecap-master/densecap/DenseCapModel.lua'
	no file '/usr/local/share/lua/5.1/densecap-master/densecap/DenseCapModel/init.lua'
	no file '/home/mrrl/.luarocks/lib/lua/5.1/densecap-master/densecap/DenseCapModel.so'
	no file '/home/mrrl/torch/install/lib/lua/5.1/densecap-master/densecap/DenseCapModel.so'
	no file '/home/mrrl/torch/install/lib/densecap-master/densecap/DenseCapModel.so'
	no file './densecap-master/densecap/DenseCapModel.so'
	no file '/usr/local/lib/lua/5.1/densecap-master/densecap/DenseCapModel.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
	[C]: in function 'error'
	/home/mrrl/torch/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
	run_model.lua:5: in main chunk
	[C]: in function 'dofile'
	...mrrl/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00406980


can you help me?
