### ISSUE TITLE
A problem in function 'multinomial' at ./densecap/modules/BoxSampler.lua:141

### ISSUE THREAD

**Issue by taey16** [jcjohnson/densecap#8]
@jcjohnson 
Hi,
I ran your nice code and met following error in training.
(We downloaded the visual-genome dataset(i.e. raw images and region descriptions) and then generate both h5, json files using the code, preprocess.py)

iter 11235: mid_box_reg_loss: 0.001, captioning_loss: 22.173, end_objectness_loss: 0.041, mid_objectness_loss: 0.106, end_box_reg_loss: 0.002,  [total: 44.644]
iter 11240: mid_box_reg_loss: 0.001, captioning_loss: 28.484, end_objectness_loss: 0.045, mid_objectness_loss: 0.050, end_box_reg_loss: 0.001,  [total: 57.159]
/home/digits/torch/install/bin/luajit: bad argument #2 to '?' (out of bounds at /home/digits/torch/pkg/torch/lib/TH/generic/THStorage.c:178)
stack traceback:
	[C]: at 0x7f24927ea8e0
	[C]: in function 'multinomial'
	./densecap/modules/BoxSampler.lua:141: in function 'forward'
	./densecap/modules/BoxSamplerHelper.lua:78: in function 'forward'
	./densecap/LocalizationLayer.lua:426: in function 'f'
	./densecap/LocalizationLayer.lua:228: in function 'timeit'
	./densecap/LocalizationLayer.lua:425: in function 'updateOutput'
	/home/digits/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
	./densecap/DenseCapModel.lua:262: in function 'forward'
	./densecap/DenseCapModel.lua:393: in function 'forward_backward'
	train.lua:98: in function 'lossFun'
	train.lua:135: in main chunk
	[C]: in function 'dofile'
	...gits/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00406670

Please give me advices to resolve the problem.

**Comment by BestSonny** [comment]
@taey16  [#418](https://github.com/torch/torch7/issues/418) should fix the error
